#+title: Todo

* Now
- [-] migrate to koota
  - [X] use koota queries for draw() method?
  - [ ] look for other fields to move into koota
  - [ ] remove all newly unused fields

- [ ] make the player a more normal entity
  ie avoid singletons

- [-] now it's too bright on the CRT
  - [X] try re-darkening object colors
    this results in sides appearing to drop out again
  - [ ] try reducing ambient light
  - [ ] try dimming the moon

- [ ] need to get something visual to demo

* Soon
- [ ] restart the game on death
  - [ ] pause music
    later, let it keep playing with an effect on it to show you're dead
  - [ ] after a timer, restart the game and the music

- [ ] Level Editor
  - show waveform with tracker line
  - show spawn/dodge times for individual obstacles

- [ ] add animated stars background

- [ ] switch to using koota?
  what other components would this game have?
  ie, is it complex enough to warrant an ECS?
  - background elements (ie the stars)
  - the camera / camera effects

* Someday
- [ ] maybe have the renderer also use koota for its d.vec types?
  is that compatible with typegpu at all?
  maybe this is a reason to go to slang? or would plain webgpu still want arrays?

- [ ] is there a nicer way to regenerate polygon sides?
  use i + apothem + halfLen to spawn & update koota components?
  maybe a relation with metadata?
  will need a way to lerp sides between two polygons
    like a square opens into a gapped pentagon
    does the current way of regenerating make that easier?
